### ISSUE TITLE
craigbalsamfromkidzbopofficial

### ISSUE THREAD

**Issue by CoreParadox** [HiiJax/Webfishing-Ban-List#1]
### SteamID

76561199139246029

### Link to Steam Profile

https://steamcommunity.com/id/craigbalsamfromkidzbopofficial

### Steam Profile Name

Craig Balsam

### Reasoning

Spam Joining a code-only lobby, odd behaivor

### Extra Details

![image](https://github.com/user-attachments/assets/d38d7c86-088b-4121-b53c-533000256a04)
![image](https://github.com/user-attachments/assets/924ef8e2-b2f8-4fe9-86a7-aa5b61698e7d)

**Comment by HiiJax** [comment]
Added! Thank you!
