### ISSUE TITLE
a bot that doesnt let users into server

### ISSUE THREAD

**Issue by talkomatic-donjamie** [HiiJax/Webfishing-Ban-List#2]
### SteamID

76561198312342854

### Link to Steam Profile

https://steamcommunity.com/profiles/76561198312342854/

### Steam Profile Name

★ drycable

### Reasoning

they are a bot pretty sure because i cant join without a mod to let me join anyway

### Extra Details

![image](https://github.com/user-attachments/assets/19aecc1e-26ce-4c5c-8e5b-dd92da44e6d6)

**Comment by HiiJax** [comment]
Added, thank you!
