### ISSUE TITLE
user spams join room

### ISSUE THREAD

**Issue by talkomatic-donjamie** [HiiJax/Webfishing-Ban-List#3]
### SteamID

76561199812719861

### Link to Steam Profile

https://steamcommunity.com/id/JohnWebfishing/

### Steam Profile Name

John Webfishing

### Reasoning

spams joinroom liek mostly

### Extra Details

![image](https://github.com/user-attachments/assets/c1051a58-3eea-4c66-9b5b-a09854635053)

**Comment by HiiJax** [comment]
Added, thanks again!
